#!/usr/bin/env bash
# Installs and setup haproxy

apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.8
apt-get -y update
apt-get install -y haproxy=1.8.\*

# echo "ENABLED=1" > /etc/default/haproxy

#Listen to web1 and web2 servers using roundrobin technique
echo '
   frontend kelton-glitch.tech
        bind 0:80
        default_backend wed_servers
   
   backend web_servers
        balance roundrobin
        server 103975-web-01 100.25.13.115:80
        server 103975-web-02 52.90.15.63:80
' >> /etc/haproxy/haproxy.cfg

service haproxy start
