#!/usr/bin/env bash
# Installs and setup haproxy

apt-get -y update
apt-get install -y haproxy=1.6.\*


#Listen to web1 and web2 servers using roundrobin technique
echo '
   frontend kelton-glitch.tech
        bind 0:80
        default_backend web_servers
   
   backend web_servers
        balance roundrobin
        server 103975-web-01 100.25.13.115:80
        server 103975-web-02 52.90.15.63:80
' >> /etc/haproxy/haproxy.cfg

service haproxy restart
