#!/usr/bin/env bash
# Block all incoming traffic but allow established connections
#+ except for TCP ports 22, 443 and 80.

apt-get install ufw
sed -i 's/IPV6=yes/IPV6=no/g' /etc/default/ufw
ufw disable
ufw enable
ufw default deny incoming
ufw default allow outgoing
ufw allow 22/tcp
ufw allow 443/tcp
ufw allow 80/tcp
