#!/usr/bin/env bash
# FIxes a web server to run Nginx as the Nginx user listening on all active IPs on port 8080
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx start
sudo -u nginx service nginx status
